version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
  mock-api:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"
